1 Jungle Level, 1 Desert Level, 1 Crystal Cave Level
EggsAndBakey/TropicalParadise0.5 pull request #1
Opened 2024-08-15 22:08 UTC by convival9

_**And also an updated README.md**_

2024-08-15 22:14 UTC, EggsAndBakey commented on Tropical_Paradise_Sefevi/coldfire.stl
Why are there snow particles in this level? Also I feel like the name doesn't exactly make sense.

2024-08-15 22:14 UTC, EggsAndBakey commented on Tropical_Paradise_Sefevi/dancinginforest.stl
Interesting and cool but the tree tiling looks sort of weird

2024-08-15 22:17 UTC, EggsAndBakey commented on Tropical_Paradise_Sefevi/tropicalcrystals.stl
Tux falls at the end of the level

2024-08-15 22:18 UTC, EggsAndBakey requested changes
Yeah so there's some stuff that needs changing but thanks for the cool levels!

2024-08-15 22:36 UTC, convival9 commented on Tropical_Paradise_Sefevi/coldfire.stl
A lot of that is most likely from how this level used to be a snow level.

2024-08-15 22:36 UTC, convival9 commented on Tropical_Paradise_Sefevi/dancinginforest.stl
Did you notice the reggTux reference? Also yeah I know about the tree tiling, that's the best I could do.

2024-08-15 22:37 UTC, convival9 commented on Tropical_Paradise_Sefevi/tropicalcrystals.stl
Oops D:

2024-08-15 23:53 UTC, convival9 commented
Fixed everything that was listed and also updated Tropical Crystals :D

2024-08-16 00:37 UTC, EggsAndBakey commented on Tropical_Paradise_Sefevi/dancinginforest.stl
That's why I said interesting, also, since this has changed since last view, a tiling error is gone so that's good.

2024-08-16 00:37 UTC, EggsAndBakey approved these changes
It seems to be fixed now, nice!

2024-08-16 00:38 UTC, merged